### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by leebaird** [BuffaloWill/Serpico#1]
Running on Kali Linux 64-bit.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb 
```

checking for sqlite3.h... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/ruby1.9.1
    --with-sqlite3-dir
    --without-sqlite3-dir
    --with-sqlite3-include
    --without-sqlite3-include=${sqlite3-dir}/include
    --with-sqlite3-lib
    --without-sqlite3-lib=${sqlite3-dir}/lib

Gem files will remain installed in /var/lib/gems/1.9.1/gems/do_sqlite3-0.10.12 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/do_sqlite3-0.10.12/ext/do_sqlite3/gem_make.out
An error occurred while installing do_sqlite3 (0.10.12), and Bundler cannot continue.
Make sure that `gem install do_sqlite3 -v '0.10.12'` succeeds before bundling.

**Comment by akaparos** [comment]
Hi will, i am unable to install serpico as always when i am trying to install on kali i first update my ruby version but i am getting an error "your ruby version is 2.3.3 and gem specified is 2.3.5..please help
