### ISSUE TITLE
Support CVSS Scoring in a Finding

### ISSUE THREAD

**Issue by BuffaloWill** [BuffaloWill/Serpico#5]
Currently when a user adds or creates a finding they score/rate the risk based on DREAD. This enhancement would add the capability to score the finding using CVSS.

**Comment by pentestgou1** [comment]
Is CVSS still unseported? It seems there is a template, but findings can not be classified using CVSS

**Comment by Petessss** [comment]
Did you enable CVSS? This can be done editing the config.json and setting cvss to true.
